### ISSUE TITLE
sign in with facebook

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#92] opened 2016-03-22 15:22 UTC
summary:
It gives this error when I try and sign in with my facebook account

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by bartmika** [comment] 2016-03-22 15:41
Currently, we are using Facebook QA access. We will need to set to use PROD.

**Comment by rodolfomartinez** [comment] 2016-03-22 15:52
Can we please do this today? I want to be able to show this to others and
there instinct will be facebook

On Tue, Mar 22, 2016 at 11:41 AM, Bartlomiej Mika <notifications@github.com>
wrote:

> Currently, we are using Facebook QA access. We will need to set to use
> PROD.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Oinweb/py-fly/issues/92#issuecomment-199872180>
>



-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !

**Comment by bartmika** [comment] 2016-03-22 16:06
Alright, according to facebook (see pic below) that we are live with PROD. It should work now. I'll test out later to confirm and then close this ticket.

![screen shot 2016-03-22 at 12 05 03 pm](https://cloud.githubusercontent.com/assets/5767602/13958430/6ceebc26-f026-11e5-8505-b9a469b5af9b.png)

**Comment by bartmika** [comment] 2016-03-22 22:43
I have just logged in w/ FaceBook social. I cannot reproduce this issue. Granted I did login using the new PROD settings. It worked. I will thus close this issue.

**Closed by bartmika** 2016-03-22 22:43 UTC
Labels: bug
